**Reasons why a loan could be rejected:**
* Credit score was too low
* Debt-to-income ratio was too high
* Tried to borrow too much
* Income was insufficient or unstable
* Didn’t meet the basic requirements
* Missing information on the application
* Loan purpose didn’t meet the lender’s criteria

[Reference](https://www.lendingtree.com/personal/reasons-why-your-personal-loan-was-declined/)


In [ ]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [ ]:
df = pd.read_csv('Bondora_raw.csv')

In [ ]:
df.head()

ReportAsOfEOD                                LoanId  LoanNumber  \
0    2020-01-27  F0660C80-83F3-4A97-8DA0-9C250112D6EC         659   
1    2020-01-27  978BB85B-1C69-4D51-8447-9C240104A3A2         654   
2    2020-01-27  EA44027E-7FA7-4BB2-846D-9C1F013C8A22         641   
3    2020-01-27  CE67AD25-2951-4BEE-96BD-9C2700C61EF4         668   
4    2020-01-27  9408BF8C-B159-4D6A-9D61-9C2400A986E3         652   

           ListedOnUTC     BiddingStartedOn  BidsPortfolioManager  BidsApi  \
0  2009-06-11 16:40:39  2009-06-11 16:40:39                     0        0   
1  2009-06-10 15:48:57  2009-06-10 15:48:57                     0        0   
2  2009-06-05 19:12:29  2009-06-05 19:12:29                     0        0   
3  2009-06-13 12:01:20  2009-06-13 12:01:20                     0        0   
4  2009-06-10 10:17:13  2009-06-10 10:17:13                     0        0   

   BidsManual  UserName  NewCreditCustomer  ...  \
0    115.0410      KARU               True  ...   
1    140.6057  koort681              False  ...   
2    319.5580       0ie               True  ...   
3     57.5205    Alyona               True  ...   
4    319.5582       Kai               True  ...   

  PreviousEarlyRepaymentsCountBeforeLoan GracePeriodStart GracePeriodEnd  \
0                                      0              NaN            NaN   
1                                      0              NaN            NaN   
2                                      0              NaN            NaN   
3                                      0              NaN            NaN   
4                                      0              NaN            NaN   

  NextPaymentDate NextPaymentNr NrOfScheduledPayments  ReScheduledOn  \
0             NaN           NaN                   NaN            NaN   
1             NaN           NaN                   NaN            NaN   
2             NaN           NaN                   NaN            NaN   
3             NaN           NaN                   NaN            NaN   
4             NaN           NaN                   NaN            NaN   

   PrincipalDebtServicingCost  InterestAndPenaltyDebtServicingCost  \
0                         0.0                                  0.0   
1                         0.0                                  0.0   
2                         0.0                                  0.0   
3                         0.0                                  0.0   
4                         0.0                                  0.0   

   ActiveLateLastPaymentCategory  
0                            NaN  
1                            NaN  
2                           180+  
3                            NaN  
4                           180+  

[5 rows x 112 columns]

In [ ]:
df.shape

(134529, 112)

This Dataset has 134529 records and 112 columns.

In [ ]:
df.describe()

LoanNumber  BidsPortfolioManager        BidsApi     BidsManual  \
count  1.345290e+05         134529.000000  134529.000000  134529.000000   
mean   9.449392e+05            966.452876      29.111664     559.332590   
std    4.786738e+05           1355.686016     150.159148     750.360512   
min    3.700000e+01              0.000000       0.000000       0.000000   
25%    6.206790e+05            155.000000       0.000000      96.000000   
50%    9.235970e+05            465.000000       0.000000     317.000000   
75%    1.311025e+06           1218.000000       5.000000     729.000000   
max    1.855339e+06          10625.000000    7570.000000   10630.000000   

       ApplicationSignedHour  ApplicationSignedWeekday  VerificationType  \
count          134529.000000             134529.000000     134484.000000   
mean               13.374640                  3.907908          2.817257   
std                 4.992375                  1.726192          1.407908   
min                 0.000000                  1.000000          0.000000   
25%                10.000000                  2.000000          1.000000   
50%                13.000000                  4.000000          4.000000   
75%                17.000000                  5.000000          4.000000   
max                23.000000                  7.000000          4.000000   

        LanguageCode            Age         Gender  ...  \
count  134529.000000  134529.000000  134484.000000  ...   
mean        2.827874      40.819295       0.442097  ...   
std         1.959802      12.348693       0.636083  ...   
min         1.000000       0.000000       0.000000  ...   
25%         1.000000      31.000000       0.000000  ...   
50%         3.000000      40.000000       0.000000  ...   
75%         4.000000      50.000000       1.000000  ...   
max        22.000000      77.000000       2.000000  ...   

       InterestAndPenaltyBalance  NoOfPreviousLoansBeforeLoan  \
count              134529.000000                134529.000000   
mean                  701.567107                     1.487620   
std                  2514.595572                     2.396148   
min                    -2.660000                     0.000000   
25%                     0.000000                     0.000000   
50%                     0.000000                     1.000000   
75%                   202.900000                     2.000000   
max                 64494.770000                    25.000000   

       AmountOfPreviousLoansBeforeLoan  PreviousRepaymentsBeforeLoan  \
count                    134529.000000                  91368.000000   
mean                       2868.652401                    928.395548   
std                        4507.046575                   2042.348751   
min                           0.000000                      0.000000   
25%                           0.000000                      0.000000   
50%                         396.354100                    197.980000   
75%                        4250.000000                    780.950000   
max                       53762.000000                  34077.420000   

       PreviousEarlyRepaymentsBefoleLoan  \
count                       58026.000000   
mean                          320.743805   
std                          1561.799076   
min                             0.000000   
25%                             0.000000   
50%                             0.000000   
75%                             0.000000   
max                         48100.000000   

       PreviousEarlyRepaymentsCountBeforeLoan  NextPaymentNr  \
count                           134529.000000   97788.000000   
mean                                 0.069903       5.178795   
std                                  0.359461       7.674427   
min                                  0.000000       0.000000   
25%                                  0.000000       0.000000   
50%                                  0.000000       3.000000   
75%                                 

In [ ]:
df.columns

Index(['ReportAsOfEOD', 'LoanId', 'LoanNumber', 'ListedOnUTC',
       'BiddingStartedOn', 'BidsPortfolioManager', 'BidsApi', 'BidsManual',
       'UserName', 'NewCreditCustomer',
       ...
       'PreviousEarlyRepaymentsCountBeforeLoan', 'GracePeriodStart',
       'GracePeriodEnd', 'NextPaymentDate', 'NextPaymentNr',
       'NrOfScheduledPayments', 'ReScheduledOn', 'PrincipalDebtServicingCost',
       'InterestAndPenaltyDebtServicingCost', 'ActiveLateLastPaymentCategory'],
      dtype='object', length=112)

In [ ]:
numerical_columns = df.select_dtypes(include=['float64','int64']).columns.to_list()

**Impute with median value:** For the numerical column, you can also replace the missing values with median values. In case you have extreme values such as outliers it is advisable to use the median approach.

In [ ]:
numerical_columns

['BidsPortfolioManager',
 'BidsApi',
 'BidsManual',
 'ApplicationSignedHour',
 'ApplicationSignedWeekday',
 'VerificationType',
 'LanguageCode',
 'Age',
 'Gender',
 'AppliedAmount',
 'Amount',
 'Interest',
 'LoanDuration',
 'MonthlyPayment',
 'UseOfLoan',
 'Education',
 'MaritalStatus',
 'EmploymentStatus',
 'OccupationArea',
 'HomeOwnershipType',
 'IncomeFromPrincipalEmployer',
 'IncomeFromPension',
 'IncomeFromFamilyAllowance',
 'IncomeFromSocialWelfare',
 'IncomeFromLeavePay',
 'IncomeFromChildSupport',
 'IncomeOther',
 'IncomeTotal',
 'ExistingLiabilities',
 'LiabilitiesTotal',
 'RefinanceLiabilities',
 'DebtToIncome',
 'FreeCash',
 'MonthlyPaymentDay',
 'PlannedInterestTillDate',
 'ExpectedLoss',
 'LossGivenDefault',
 'ExpectedReturn',
 'ProbabilityOfDefault',
 'PrincipalOverdueBySchedule',
 'ModelVersion',
 'PrincipalPaymentsMade',
 'InterestAndPenaltyPaymentsMade',
 'PrincipalBalance',
 'InterestAndPenaltyBalance',
 'NoOfPreviousLoansBeforeLoan',
 'AmountOfPreviousLoansBeforeLoa

In [ ]:
df.dtypes

ReportAsOfEOD                              object
BidsPortfolioManager                        int64
BidsApi                                     int64
BidsManual                                float64
NewCreditCustomer                            bool
                                           ...   
AmountOfPreviousLoansBeforeLoan           float64
PreviousRepaymentsBeforeLoan              float64
PreviousEarlyRepaymentsCountBeforeLoan      int64
NextPaymentNr                             float64
NrOfScheduledPayments                     float64
Length: 71, dtype: object

In [ ]:
len(numerical_columns)

51

**Impute with mode value:** For the categorical column, We can replace the missing values with mode values i.e the frequent ones.

In [ ]:
categorical_columns = df.select_dtypes(include=['object','bool']).columns.to_list()

In [ ]:
categorical_columns

['ReportAsOfEOD',
 'NewCreditCustomer',
 'LoanApplicationStartedDate',
 'LoanDate',
 'FirstPaymentDate',
 'MaturityDate_Original',
 'MaturityDate_Last',
 'DateOfBirth',
 'Country',
 'County',
 'City',
 'EmploymentDurationCurrentEmployer',
 'ActiveScheduleFirstPaymentReached',
 'LastPaymentOn',
 'StageActiveSince',
 'Rating',
 'Status',
 'Restructured',
 'WorseLateCategory',
 'CreditScoreEsMicroL']

In [ ]:
len(categorical_columns)

20

In [ ]:
from sklearn.impute import SimpleImputer

num_imp = SimpleImputer(strategy = 'median')
df[numerical_columns]= num_imp.fit_transform(df[numerical_columns])

cat_imp = SimpleImputer(strategy = 'most_frequent')
df[categorical_columns]= cat_imp.fit_transform(df[categorical_columns])

In [ ]:
mi_scores['InterestAndPenaltyBalance']

0.6785910205972808

In [ ]:
low_mi_score_col = []
for i in X.columns:
  if mi_scores[i] < 0.05:
    print(f'Removing the {i} column')
    low_mi_score_col.append(i)
    X.drop(columns = [i], inplace = True)

Removing the BidsPortfolioManager column
Removing the BidsApi column
Removing the BidsManual column
Removing the ApplicationSignedHour column
Removing the ApplicationSignedWeekday column
Removing the VerificationType column
Removing the LanguageCode column
Removing the Age column
Removing the Gender column
Removing the Amount column
Removing the UseOfLoan column
Removing the Education column
Removing the MaritalStatus column
Removing the EmploymentStatus column
Removing the OccupationArea column
Removing the HomeOwnershipType column
Removing the IncomeFromPrincipalEmployer column
Removing the IncomeFromPension column
Removing the IncomeFromFamilyAllowance column
Removing the IncomeFromSocialWelfare column
Removing the IncomeFromLeavePay column
Removing the IncomeFromChildSupport column
Removing the IncomeOther column
Removing the IncomeTotal column
Removing the ExistingLiabilities column
Removing the LiabilitiesTotal column
Removing the RefinanceLiabilities column
Removing the DebtToIn

In [ ]:
X.shape

(77394, 27)

In [ ]:
X.columns

Index(['AppliedAmount', 'Interest', 'LoanDuration', 'MonthlyPayment',
       'PlannedInterestTillDate', 'ExpectedLoss', 'LossGivenDefault',
       'ExpectedReturn', 'ProbabilityOfDefault', 'PrincipalOverdueBySchedule',
       'PrincipalPaymentsMade', 'InterestAndPenaltyPaymentsMade',
       'PrincipalBalance', 'InterestAndPenaltyBalance', 'NextPaymentNr',
       'NrOfScheduledPayments', 'LoanApplicationStartedDate_year',
       'FirstPaymentDate_year', 'MaturityDate_Original_year',
       'MaturityDate_Last_year', 'LastPaymentOn_year', 'LastPaymentOn_month',
       'LastPaymentOn_week', 'StageActiveSince_year', 'StageActiveSince_month',
       'StageActiveSince_week', 'StageActiveSince_day'],
      dtype='object')

In [ ]:
X.shape

(77394, 27)

In [ ]:
X.head()

AppliedAmount  Interest  LoanDuration  MonthlyPayment  \
0       319.5582      30.0          12.0           97.38   
1       191.7349      25.0           1.0           97.38   
2       319.5582      25.0          20.0           97.38   
3       127.8233      45.0          15.0           97.38   
4       319.5582      30.0          12.0           97.38   

   PlannedInterestTillDate  ExpectedLoss  LossGivenDefault  ExpectedReturn  \
0                 319.0800      0.123398          0.506748        0.134049   
1                  45.8300      0.123398          0.506748        0.134049   
2                 197.2926      0.123398          0.506748        0.134049   
3                 293.1000      0.123398          0.506748        0.134049   
4                 833.8100      0.123398          0.506748        0.134049   

   ProbabilityOfDefault  PrincipalOverdueBySchedule  ...  \
0               0.23414                        0.00  ...   
1               0.23414                        0.00  ...   
2               0.23414                      116.35  ...   
3               0.23414                        0.00  ...   
4               0.23414                        0.00  ...   

   FirstPaymentDate_year  MaturityDate_Original_year  MaturityDate_Last_year  \
0                   2009                        2010                    2010   
1                   2009                        2009                    2009   
2                   2009                        2011                    2014   
3                   2009                        2010                    2010   
4                   2009                        2010                    2010   

   LastPaymentOn_year  LastPaymentOn_month  LastPaymentOn_week  \
0                2010                    7                  27   
1                2009                    7                  28   
2                2012                   10                  40   
3                2010                    9                  37   
4                2015                    7                  29   

   StageActiveSince_year  StageActiveSince_month  StageActiveSince_week  \
0                   2019                       2                      6   
1                   2019                       2                      6   
2                   2016                       3                      9   
3                   2019                       2                      6   
4                   2019                       2                      6   

   StageActiveSince_day  
0                     8  
1                     8  
2                     3  
3                     8  
4                     8  

[5 rows x 27 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

In [ ]:
from sklearn.preprocessing import Normalizer
scale = Normalizer()
x_train = scale.fit_transform(x_train)
x_test = scale.transform(x_test)

## Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Fit the logistic regression model
clf = LogisticRegression()
clf.fit(x_train, y_train)

# Make predictions on the test set
y_pred = clf.predict(x_test)

# Calculate the model's performance metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

## Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(random_state=42, n_jobs=-1, max_depth=5,
                                       n_estimators=100, oob_score=True)
classifier_rf.fit(x_train, y_train)

classifier_rf.oob_score_

0.9999515464750061

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(max_depth=2, min_samples_leaf=5, n_jobs=-1,
                                       random_state=42, n_estimators=100, oob_score=True)

classifier_rf.fit(x_train, y_train)

classifier_rf.oob_score_

0.9986433013001695

In [ ]:
y_pred = classifier_rf.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)